# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'example' do
  # pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  # pod 'React', :path => '../node_modules/react-native', :subspecs => [ 'Core', 'DevSupport', 'RCTText', 'RCTNetwork', 'RCTWebSocket', ]
  # pod 'react-native-skyway', path: '../../'
  pod 'SkyWay'
  inherit! :search_paths
end
